# bundle exec jekyll serve --host=0.0.0.0

title: MycilaTrafficLight
description: ESP32 / Arduino Library for Traffic Light LEDs
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
